---
- name: Check firewall management tool available
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - ufw
    - iptables

- name: Gather current firewall status
  ansible.builtin.command: ufw status verbose
  register: ufw_status
  changed_when: false
  ignore_errors: true

- name: Display current firewall status
  ansible.builtin.debug:
    var: ufw_status.stdout_lines
